name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  DaaC:
    runs-on: ubuntu-latest

    steps:
      - name: Apply modified or new decoder file(s) to SIEM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Copying updated files to Wazuh ruleset..."
            git pull origin main || true
            echo "Ruleset update added!!!"

            sudo systemctl restart wazuh-manager || true
            echo "wazuh-manager service restarted!!!"
            echo "Ruleset applied!!!"